version: '3'
services:
  app:
    image: node:12
    volumes:
      - .:/app/
    ports:
      - 3000:3000
    depends_on:
      - postgres
    working_dir: /app
    command: npm run start:debug
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: database
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres:
